$LOAD_PATH.unshift File.expand_path('../../../lib', __FILE__)
Vagrant.require_plugin 'vagrant-foodtaster-server'
SERVER_IP = '10.0.2.15'

Vagrant.configure("2") do |config|
  config.vm.box = "test"
  config.vm.box_url = "test.box"
  config.vm.network 'private_network', ip: SERVER_IP
  # move them to box
  config.vm.provision :shell,
    inline: 'sudo apt-get install -y curl'
  config.vm.provision :shell,
    inline: 'curl -L https://www.opscode.com/chef/install.sh | sudo bash'
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = %w[../fixtures/cookbooks]
  end
  #config.vm.network 'forwarded_port', host: 4444, guest: 4444
end
